import { defineField } from "sanity";

const user = {
  name: "user",
  title: "user",
  type: "document",
  fields: [
    defineField({
      name: "isAdmin",
      title: "Is Admin",
      type: "boolean",
      description: "Check if the user is admin",
      initialValue: false,
      validation: (Rule) => Rule.required(),
      //   readOnly: true,
      //   hidden: true,
    }),
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      description: "Name of the user",
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "firstname",
      title: "Firstname",
      type: "string",
      //   description: "Firstname of the user",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "lastname",
      title: "Lastname",
      type: "string",
      //   description: "Lastname of the user",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      //   description: "Country",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "zip",
      title: "Zip",
      type: "string",
      //   description: "Zip",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "city",
      title: "City",
      type: "string",
      //   description: "City",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "street",
      title: "Street",
      type: "string",
      //   description: "Street",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "house",
      title: "House",
      type: "string",
      //   description: "House",
      //   readOnly: true,
      //   validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "image",
      title: "Image",
      type: "url",
    }),
    defineField({
      name: "password",
      type: "string",
      //   hidden: true,
    }),
    defineField({
      name: "email",
      type: "string",
      title: "Email",
    }),
    defineField({
      name: "emailVerified",
      type: "datetime",
      //   hidden: true,
    }),
    defineField({
      name: "about",
      title: "About",
      type: "text",
      description: "A brief dsecription about the user",
    }),
  ],
};

export default user;
